### ISSUE TITLE
Support For Vite HMR 疑問

### ISSUE THREAD

**Issue by BbsonLin** [huibizhang/vitawind#1]
您好，最近剛好在學習 Tailwind + Vite，也正建立些練習專案

目前 `Easy To Install` 和 `One-Command Setting` 功能，能更方便 Tailwind 在 Vite 開發環境裡設定，很好理解。
但 `Support For Vite HMR` 這功能上有點理解不能、不太會使用，
小弟才疏學淺，不知道大大有沒有更深入的說明呢~?

**Comment by huibizhang** [comment]
沒事，因為我可能要把敘述拿掉了XD
我之前開始用 Vite 時
當時的版本我有遇到 Tailwind 開了 jit 後
改了樣式，有觸發 vite 的 hmr
但是只有觸發你所修改的檔案
css 沒有更新，所以新的樣式沒有上去
(雖然有說人他沒遇到過這個狀況)

然後經過實驗是必須讓 Tailwind 透過 postcss 開啟 watch 不斷去監控並觸發重新編譯 css，這樣才有效。

而現在的 Vite 2.3.8 對於 jit 更新的支援度更完善了，所以這個問題並不存在了

README 的敘述過一陣子的更新會拿掉
不好意思可能造成了你的誤會～

不過關於可以簡單安裝設定 Tailwind 和順利開始 jit 的這件事情不會停歇，畢竟 jit 真的很香～
之後還會陸續開發，推出在 vue-cli 還有 create-react-app 上，甚至是 vitepress 及 vuepress 或其他前端框架的 vitawind 哈哈
