### ISSUE TITLE
執行kick-off cmd失敗

### ISSUE THREAD

**Issue by sp0033212000** [huibizhang/vitawind#31]
執行 `yarn create vitawind class_cms --react-ts`後得到以下失敗原因。

yarn create v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-vitawind@0.3.4" with binaries:
      - create-vitawind
[####] 4/4env: node\r: No such file or directory
error Command failed.
Exit code: 127
Command: /usr/local/bin/create-vitawind
Arguments: class_cms --react-ts
Directory: /Users/liaojiwei/Desktop/hunger/class/class_cms
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

請問是要先install create-vitawind globally嗎？

**Comment by huibizhang** [comment]
謝謝你的 issue
您好，請問環境是 mac 或 linux 對吧?

**Comment by huibizhang** [comment]
@sp0033212000  你好！ 謝謝你的通知。

因為 yarn 只接受 LF 的換行格式，而我使用 Windows 是 CRLF。
已將格式調整修正問題並重新上傳了。

現在再重新跑一次指令試試看，感謝。

**Comment by sp0033212000** [comment]
有了，感謝您～～～

**Comment by sp0033212000** [comment]
大大，這個狀況又發生了0.0

**Comment by huibizhang** [comment]
@sp0033212000 不好意思因為剛好換電腦環境沒注意到 QQ
謝謝提醒，已修正！

**Comment by sp0033212000** [comment]
真的是辛苦大大了ＱＱ
