### ISSUE TITLE
compiler 錯誤

### ISSUE THREAD

**Issue by Michael0520** [huibizhang/vitawind#46]
## 目的

快速建立專案，進行練習 Tailwind

## 問題

執行下方指令列，執行專案後，網頁為空白，以及出現一個錯誤，下方將會貼上執行指令列以及錯誤截圖，
請問應該如何解決此問題呢？

## 執行指令列

```base
npm init vite-project -- --vue
cd maileshop
npm install
npm run dev
```

## 錯誤截圖

![CleanShot 2022-01-14 at 02 45 22](https://user-images.githubusercontent.com/60827537/149391020-4b9ba275-8cbe-42b5-a372-29631311cb8f.png)

**Comment by huibizhang** [comment]
雖然看不出來和 vitawind 的套件有什麼關係，不過這是一個好問題！

待我測試之後告訴你

_(不過也有可能是當下版本問題，我測試的時候已經沒有異狀了)_

**Comment by huibizhang** [comment]
@Michael0520 你給的指令有誤哦～ 不能安裝

如果是建立 vite 官方專案，是：
```bash
npm init vite -- maileshop --template vue
cd maileshop
npm install
npm run dev
```

如果是 vitawind，則是：
```bash
npm i -g create-vitawind@latest
npm init vitawind maileshop  -- --vue
cd maileshop
npm install
npm run dev
```
